version: "1.0"
name: 流水线-202607231401
displayName: 流水线-202607231401
stages:
- name: 未命名
  displayName: 未命名
  strategy: naturally
  trigger: auto
  steps:
  - step: shell@agent
    name: "10069559"
    displayName: Shell 脚本执行
    schedulerType: DISTRIBUTED
    scriptType: SH
    script: |-
      # 请在此输入您想执行的脚本
      echo 'Hello Gitee!'
    gitClone: "false"
    hostGroupID:
      ID: devops-share
      hostID:
      - bb8eebd2-3087-43a5-8929-f195b28f5595
    strategy:
      retry: "0"
triggers:
  trigger: auto
  push:
    branches:
      prefix:
      - master
      precise: []
      include: []
notify: []
